import { createClient } from '@supabase/supabase-js';

if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !(process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)) {
  console.error('Missing required env vars: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY or NEXT_PUBLIC_SUPABASE_ANON_KEY');
  process.exit(1);
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

const categories = [
  { slug: "pet-siseler", name: "PET Şişeler", description: "Kozmetik, kolonya ve kişisel bakım ürünleri için farklı hacim ve tasarımlarda PET şişeler.", productCount: 15 },
  { slug: "plastik-siseler", name: "Plastik Şişeler", description: "HDPE, PP ve LDPE hammaddeli dayanıklı plastik şişe çeşitleri.", productCount: 10 },
  { slug: "kapaklar", name: "Kapaklar", description: "Vidalı, flip-top ve özel tasarım kapak çeşitleri.", productCount: 8 },
  { slug: "tipalar", name: "Tıpalar", description: "İç tıpa, damlatıcı tıpa ve sızdırmazlık tıpaları.", productCount: 6 },
  { slug: "parmak-spreyler", name: "Parmak Spreyler", description: "Kozmetik ve kolonya ürünleri için parmak sprey mekanizmaları.", productCount: 5 },
  { slug: "pompalar", name: "Pompalar", description: "Losyon pompası, köpük pompası ve krem dozajlama pompaları.", productCount: 7 },
  { slug: "tetikli-pusturtuculer", name: "Tetikli Püskürtücüler", description: "Temizlik ve bakım ürünleri için tetikli püskürtme sistemleri.", productCount: 4 },
  { slug: "huniler", name: "Huniler", description: "Dolum sürecinde kullanılan plastik huniler.", productCount: 3 },
];

const products = [
  {
    slug: "pet-sise-50ml-damla",
    name: "PET Şişe 50ml Damla",
    category: "pet-siseler",
    description: "50ml damla model PET şişe. Serum, cilt bakım yağı ve göz çevresi bakım ürünleri için kompakt tasarım. 18mm ağız çapı ile damlalık veya mini pompa uyumlu.",
    shortDescription: "50ml damla model kozmetik şişe",
    volume: "50ml",
    weight: "8g",
    neckDiameter: "18mm",
    height: "105mm",
    diameter: "35mm",
    material: "PET",
    colors: ["Şeffaf", "Amber", "Füme", "Beyaz"],
    model: "Damla",
    shape: "silindir",
    minOrder: 20000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Hacim", value: "50ml" },
      { label: "Ağırlık", value: "8g" },
      { label: "Ağız", value: "18mm" },
      { label: "Yükseklik", value: "105mm" },
      { label: "Çap", value: "35mm" },
      { label: "Hammadde", value: "PET" },
      { label: "Model", value: "Damla" },
    ],
  },
  {
    slug: "pet-sise-100ml-silindir",
    name: "PET Şişe 100ml Silindir",
    category: "pet-siseler",
    description: "100ml silindir model PET şişe. Kolonya, parfüm ve kişisel bakım ürünleri için zarif silindirik tasarım. 20mm ağız çapı.",
    shortDescription: "100ml silindir kozmetik şişe",
    volume: "100ml",
    weight: "15g",
    neckDiameter: "20mm",
    height: "130mm",
    diameter: "42mm",
    material: "PET",
    colors: ["Şeffaf", "Amber", "Mavi", "Füme"],
    model: "Silindir",
    shape: "silindir",
    minOrder: 15000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Hacim", value: "100ml" },
      { label: "Ağırlık", value: "15g" },
      { label: "Ağız", value: "20mm" },
      { label: "Yükseklik", value: "130mm" },
      { label: "Çap", value: "42mm" },
      { label: "Hammadde", value: "PET" },
      { label: "Model", value: "Silindir" },
    ],
  },
  {
    slug: "pet-sise-250ml-kristal",
    name: "PET Şişe 250ml Kristal",
    category: "pet-siseler",
    description: "250ml kristal model PET şişe. Şampuan, duş jeli ve kişisel bakım ürünleri için şık kristal desen. 24mm Modern ağız.",
    shortDescription: "250ml kristal model şişe",
    volume: "250ml",
    weight: "24g",
    neckDiameter: "24mm Modern",
    height: "175mm",
    diameter: "58mm",
    material: "PET",
    colors: ["Şeffaf", "Yeşil", "Mavi", "Altın Yaldız"],
    model: "Kristal",
    shape: "silindir",
    minOrder: 10000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Hacim", value: "250ml" },
      { label: "Ağırlık", value: "24g" },
      { label: "Ağız", value: "24mm Modern" },
      { label: "Yükseklik", value: "175mm" },
      { label: "Çap", value: "58mm" },
      { label: "Hammadde", value: "PET" },
      { label: "Model", value: "Kristal" },
    ],
  },
  {
    slug: "pet-sise-500ml-duz",
    name: "PET Şişe 500ml Düz",
    category: "pet-siseler",
    description: "500ml düz model PET şişe. Şampuan, saç kremi ve sıvı sabun için yüksek hacimli düz tasarım. 28mm ağız çapı.",
    shortDescription: "500ml düz model kozmetik şişe",
    volume: "500ml",
    weight: "32g",
    neckDiameter: "28mm",
    height: "210mm",
    diameter: "68mm",
    material: "PET",
    colors: ["Şeffaf", "Beyaz", "Siyah", "Gümüş"],
    model: "Düz",
    shape: "silindir",
    minOrder: 5000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Hacim", value: "500ml" },
      { label: "Ağırlık", value: "32g" },
      { label: "Ağız", value: "28mm" },
      { label: "Yükseklik", value: "210mm" },
      { label: "Çap", value: "68mm" },
      { label: "Hammadde", value: "PET" },
      { label: "Model", value: "Düz" },
    ],
  },
  {
    slug: "hdpe-sise-200ml-silindir",
    name: "HDPE Şişe 200ml Silindir",
    category: "plastik-siseler",
    description: "200ml HDPE silindir şişe. Losyon, krem ve vücut sütü ambalajı için dayanıklı, opak yapı. 24mm Klasik ağız.",
    shortDescription: "200ml HDPE silindir şişe",
    volume: "200ml",
    weight: "21g",
    neckDiameter: "24mm Klasik",
    height: "155mm",
    diameter: "52mm",
    material: "HDPE",
    colors: ["Beyaz", "Pembe", "Mavi", "Yeşil"],
    model: "Silindir",
    shape: "silindir",
    minOrder: 10000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Hacim", value: "200ml" },
      { label: "Ağırlık", value: "21g" },
      { label: "Ağız", value: "24mm Klasik" },
      { label: "Yükseklik", value: "155mm" },
      { label: "Çap", value: "52mm" },
      { label: "Hammadde", value: "HDPE" },
      { label: "Model", value: "Silindir" },
    ],
  },
  {
    slug: "pp-sise-300ml-oval",
    name: "PP Şişe 300ml Oval",
    category: "plastik-siseler",
    description: "300ml PP oval şişe. Şampuan ve saç bakım ürünleri için esnek, sıkılabilir oval form. 24mm Modern ağız.",
    shortDescription: "300ml PP oval şişe",
    volume: "300ml",
    weight: "25.5g",
    neckDiameter: "24mm Modern",
    height: "170mm",
    diameter: "60mm",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Gümüş"],
    model: "Oval",
    shape: "oval",
    minOrder: 8000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Hacim", value: "300ml" },
      { label: "Ağırlık", value: "25.5g" },
      { label: "Ağız", value: "24mm Modern" },
      { label: "Yükseklik", value: "170mm" },
      { label: "Çap", value: "60mm" },
      { label: "Hammadde", value: "PP" },
      { label: "Model", value: "Oval" },
    ],
  },
  {
    slug: "hdpe-sise-500ml-kare",
    name: "HDPE Şişe 500ml Kare",
    category: "plastik-siseler",
    description: "500ml HDPE kare şişe. Şampuan, duş jeli ve sıvı sabun ürünleri için modern kare form. 28mm ağız çapı.",
    shortDescription: "500ml HDPE kare şişe",
    volume: "500ml",
    weight: "32g",
    neckDiameter: "28mm",
    height: "200mm",
    diameter: "70mm",
    material: "HDPE",
    colors: ["Beyaz", "Siyah", "Füme"],
    model: "Kare",
    shape: "düz",
    minOrder: 5000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Hacim", value: "500ml" },
      { label: "Ağırlık", value: "32g" },
      { label: "Ağız", value: "28mm" },
      { label: "Yükseklik", value: "200mm" },
      { label: "Çap", value: "70mm" },
      { label: "Hammadde", value: "HDPE" },
      { label: "Model", value: "Kare" },
    ],
  },
  {
    slug: "kapak-18mm-vidali",
    name: "Kapak 18mm Vidalı",
    category: "kapaklar",
    description: "18mm vidalı kapak. Serum, esansiyel yağ ve küçük kozmetik şişeler için standart vidalı kapak.",
    shortDescription: "18mm vidalı kozmetik kapak",
    neckDiameter: "18mm",
    weight: "1.5g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Altın Yaldız", "Gümüş"],
    minOrder: 50000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Çap", value: "18mm" },
      { label: "Ağırlık", value: "1.5g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Vidalı" },
    ],
  },
  {
    slug: "kapak-24mm-flip-top",
    name: "Kapak 24mm Flip-Top",
    category: "kapaklar",
    description: "24mm flip-top kapak. Şampuan, losyon ve kozmetik şişeler için tek elle açılabilen pratik kapak. Klasik ve Modern ağız uyumlu.",
    shortDescription: "24mm flip-top kozmetik kapak",
    neckDiameter: "24mm Klasik",
    weight: "3g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Pembe", "Mavi", "Şeffaf"],
    minOrder: 30000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "24mm" },
      { label: "Ağırlık", value: "3g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Flip-Top" },
      { label: "Uyumluluk", value: "24mm Klasik / Modern" },
    ],
  },
  {
    slug: "kapak-24mm-disc-top",
    name: "Kapak 24mm Disc-Top",
    category: "kapaklar",
    description: "24mm disc-top kapak. Şampuan, duş jeli ve losyon şişeleri için basmalı disc-top açma sistemi.",
    shortDescription: "24mm disc-top kozmetik kapak",
    neckDiameter: "24mm Modern",
    weight: "3.5g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Şeffaf"],
    minOrder: 30000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Çap", value: "24mm" },
      { label: "Ağırlık", value: "3.5g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Disc-Top" },
      { label: "Uyumluluk", value: "24mm Modern" },
    ],
  },
  {
    slug: "ic-tipa-18mm",
    name: "İç Tıpa 18mm",
    category: "tipalar",
    description: "18mm iç tıpa. Serum, esansiyel yağ ve kolonya şişeleri için sızdırmazlık sağlayan PE iç tıpa. Sprey ve damlalık kapak altında kullanılır.",
    shortDescription: "18mm PE iç tıpa",
    neckDiameter: "18mm",
    weight: "0.5g",
    material: "PE",
    colors: ["Beyaz", "Şeffaf"],
    minOrder: 100000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "18mm" },
      { label: "Ağırlık", value: "0.5g" },
      { label: "Hammadde", value: "PE" },
      { label: "Tip", value: "İç Tıpa" },
    ],
  },
  {
    slug: "damlatici-tipa-20mm",
    name: "Damlatıcı Tıpa 20mm",
    category: "tipalar",
    description: "20mm damlatıcı tıpa. Serum, göz damlası ve esansiyel yağ şişeleri için kontrollü damlatma sağlayan tıpa.",
    shortDescription: "20mm damlatıcı tıpa",
    neckDiameter: "20mm",
    weight: "0.8g",
    material: "PE",
    colors: ["Beyaz", "Şeffaf"],
    minOrder: 80000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "20mm" },
      { label: "Ağırlık", value: "0.8g" },
      { label: "Hammadde", value: "PE" },
      { label: "Tip", value: "Damlatıcı" },
      { label: "Delik", value: "1mm kontrollü akış" },
    ],
  },
  {
    slug: "sizdirmazlik-tipasi-24mm",
    name: "Sızdırmazlık Tıpası 24mm",
    category: "tipalar",
    description: "24mm sızdırmazlık tıpası. Losyon, şampuan ve kozmetik şişeler için flip-top ve disc-top kapak altında kullanılan sızdırmazlık elemanı.",
    shortDescription: "24mm sızdırmazlık tıpası",
    neckDiameter: "24mm Klasik",
    weight: "1g",
    material: "PE",
    colors: ["Beyaz", "Şeffaf"],
    minOrder: 80000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Çap", value: "24mm" },
      { label: "Ağırlık", value: "1g" },
      { label: "Hammadde", value: "PE" },
      { label: "Tip", value: "Sızdırmazlık" },
      { label: "Uyumluluk", value: "24mm Klasik / Modern" },
    ],
  },
  {
    slug: "parmak-sprey-18mm-ince-sis",
    name: "Parmak Sprey 18mm İnce Sis",
    category: "parmak-spreyler",
    description: "18mm parmak sprey mekanizması, ince sis tipi. Parfüm, kolonya ve küçük kozmetik şişeler için hassas püskürtme sağlar.",
    shortDescription: "18mm ince sis parmak sprey",
    neckDiameter: "18mm",
    weight: "3.5g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Altın Yaldız", "Gümüş"],
    minOrder: 30000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "18mm" },
      { label: "Ağırlık", value: "3.5g" },
      { label: "Hammadde", value: "PP" },
      { label: "Sprey Tipi", value: "İnce sis" },
      { label: "Dozaj", value: "0.1ml / basım" },
    ],
  },
  {
    slug: "parmak-sprey-20mm-standart",
    name: "Parmak Sprey 20mm Standart",
    category: "parmak-spreyler",
    description: "20mm parmak sprey mekanizması. Kolonya, vücut spreyi ve oda parfümü şişeleri için standart sprey başlığı.",
    shortDescription: "20mm standart parmak sprey",
    neckDiameter: "20mm",
    weight: "4g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Gümüş", "Altın Yaldız"],
    minOrder: 25000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "20mm" },
      { label: "Ağırlık", value: "4g" },
      { label: "Hammadde", value: "PP" },
      { label: "Sprey Tipi", value: "Standart sis" },
      { label: "Dozaj", value: "0.15ml / basım" },
    ],
  },
  {
    slug: "parmak-sprey-24mm-parfum",
    name: "Parmak Sprey 24mm Parfüm",
    category: "parmak-spreyler",
    description: "24mm parmak sprey mekanizması, parfüm tipi. Büyük hacimli kolonya ve kozmetik sprey şişeleri için güçlü püskürtme kapasitesi.",
    shortDescription: "24mm parfüm tipi parmak sprey",
    neckDiameter: "24mm Klasik",
    weight: "5g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Gümüş"],
    minOrder: 20000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Çap", value: "24mm" },
      { label: "Ağırlık", value: "5g" },
      { label: "Hammadde", value: "PP" },
      { label: "Sprey Tipi", value: "Parfüm" },
      { label: "Dozaj", value: "0.2ml / basım" },
    ],
  },
  {
    slug: "losyon-pompasi-28mm",
    name: "Losyon Pompası 28mm",
    category: "pompalar",
    description: "28mm losyon pompası. Sıvı sabun, losyon ve şampuan şişeleri için dozajlı pompa mekanizması. Uzun borusu ile 500ml şişeye kadar uyumlu.",
    shortDescription: "28mm losyon dozajlama pompası",
    neckDiameter: "28mm",
    weight: "8g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Gümüş", "Altın Yaldız"],
    minOrder: 20000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "28mm" },
      { label: "Ağırlık", value: "8g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Losyon Pompası" },
      { label: "Dozaj", value: "1ml / basım" },
      { label: "Boru Uzunluğu", value: "195mm" },
    ],
  },
  {
    slug: "kopuk-pompasi-28mm",
    name: "Köpük Pompası 28mm",
    category: "pompalar",
    description: "28mm köpük pompası. El yıkama sıvısı ve yüz temizleme köpüğü şişeleri için hava karışımlı köpük üreten pompa mekanizması.",
    shortDescription: "28mm köpük üretim pompası",
    neckDiameter: "28mm",
    weight: "10g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Şeffaf"],
    minOrder: 15000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "28mm" },
      { label: "Ağırlık", value: "10g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Köpük Pompası" },
      { label: "Dozaj", value: "0.8ml / basım" },
      { label: "Mesh", value: "Çift filtreli" },
    ],
  },
  {
    slug: "krem-pompasi-24mm",
    name: "Krem Pompası 24mm",
    category: "pompalar",
    description: "24mm krem dozajlama pompası. Yoğun kıvamlı losyon, krem ve saç bakım ürünleri için güçlü emme kapasiteli pompa.",
    shortDescription: "24mm krem dozajlama pompası",
    neckDiameter: "24mm Modern",
    weight: "7g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Gümüş"],
    minOrder: 20000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Çap", value: "24mm" },
      { label: "Ağırlık", value: "7g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Krem Pompası" },
      { label: "Dozaj", value: "1.5ml / basım" },
      { label: "Boru Uzunluğu", value: "165mm" },
    ],
  },
  {
    slug: "tetikli-puskurtucu-28mm-standart",
    name: "Tetikli Püskürtücü 28mm Standart",
    category: "tetikli-pusturtuculer",
    description: "28mm standart tetikli püskürtücü. Temizlik sıvıları, cam silici ve çok amaçlı sprey ürünleri için ayarlanabilir nozul ile sis ve jet modları.",
    shortDescription: "28mm standart tetikli püskürtücü",
    neckDiameter: "28mm",
    weight: "25g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Mavi", "Yeşil"],
    minOrder: 10000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "28mm" },
      { label: "Ağırlık", value: "25g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Standart Tetikli" },
      { label: "Dozaj", value: "1.2ml / basım" },
      { label: "Mod", value: "Sis / Jet / Kapalı" },
    ],
  },
  {
    slug: "tetikli-puskurtucu-28mm-kopuklu",
    name: "Tetikli Püskürtücü 28mm Köpüklü",
    category: "tetikli-pusturtuculer",
    description: "28mm köpüklü tetikli püskürtücü. Banyo ve mutfak temizleyicileri için köpük modlu, güçlü püskürtme kapasiteli tetik mekanizması.",
    shortDescription: "28mm köpüklü tetikli püskürtücü",
    neckDiameter: "28mm",
    weight: "28g",
    material: "PP",
    colors: ["Beyaz", "Siyah", "Mavi"],
    minOrder: 10000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Çap", value: "28mm" },
      { label: "Ağırlık", value: "28g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Köpüklü Tetikli" },
      { label: "Dozaj", value: "1.5ml / basım" },
      { label: "Mod", value: "Köpük / Jet / Kapalı" },
    ],
  },
  {
    slug: "plastik-huni-30mm",
    name: "Plastik Huni 30mm",
    category: "huniler",
    description: "30mm ağız çaplı plastik huni. Küçük hacimli kozmetik, parfüm ve serum şişelerine dolum işlemleri için ideal. PP hammaddeli, tekrar kullanılabilir.",
    shortDescription: "30mm kozmetik dolum hunisi",
    diameter: "30mm",
    weight: "2g",
    material: "PP",
    colors: ["Beyaz", "Şeffaf"],
    minOrder: 50000,
    inStock: true,
    featured: true,
    specs: [
      { label: "Ağız Çapı", value: "30mm" },
      { label: "Ağırlık", value: "2g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Mini Huni" },
    ],
  },
  {
    slug: "plastik-huni-50mm",
    name: "Plastik Huni 50mm",
    category: "huniler",
    description: "50mm ağız çaplı plastik huni. Orta ve büyük hacimli şişelere dolum işlemleri için geniş ağızlı, hızlı akışlı tasarım.",
    shortDescription: "50mm geniş ağızlı dolum hunisi",
    diameter: "50mm",
    weight: "4g",
    material: "PP",
    colors: ["Beyaz", "Şeffaf"],
    minOrder: 30000,
    inStock: true,
    featured: false,
    specs: [
      { label: "Ağız Çapı", value: "50mm" },
      { label: "Ağırlık", value: "4g" },
      { label: "Hammadde", value: "PP" },
      { label: "Tip", value: "Standart Huni" },
    ],
  },
];

const blogPosts = [
  {
    slug: "pet-sise-uretim-sureci",
    title: "PET Şişe Üretim Süreci: Hammaddeden Ürüne",
    excerpt: "PET şişelerin üretim aşamalarını, kullanılan teknolojileri ve kalite kontrol süreçlerini detaylı olarak inceliyoruz.",
    content: [
      "PET (Polietilen Tereftalat), günümüzde en yaygın kullanılan ambalaj malzemelerinden biridir. Hafifliği, şeffaflığı, geri dönüştürülebilirliği ve mükemmel bariyer özellikleri sayesinde kozmetik, parfümeri ve kişisel bakım sektörlerinde tercih edilmektedir.",
      "PET şişe üretim süreci temel olarak iki ana aşamadan oluşur: preform üretimi (enjeksiyon kalıplama) ve şişe üretimi (şişirme kalıplama). Her iki aşama da yüksek hassasiyet ve kalite kontrol gerektirir.",
      "İlk aşamada, PET granüller kurutma fırınlarında nem oranı optimum seviyeye getirilir. Ardından enjeksiyon makinelerinde eritilerek preform kalıplarına enjekte edilir. Elde edilen preformlar, şişirme aşamasına hazır hale getirilir.",
      "Şişirme aşamasında, preformlar özel fırınlarda ısıtılarak yumuşatılır ve yüksek basınçlı hava ile kalıp içinde şişirilir. Bu işlem, preformu istenen şişe şekline dönüştürür. Sıcaklık, basınç ve zamanlama parametreleri ürün kalitesini doğrudan etkiler.",
      "Üretim sürecinin her aşamasında kapsamlı kalite kontroller uygulanır: boyutsal ölçüm, basınç dayanım testi, sızdırmazlık testi, düşme testi ve görsel kontrol. Bu testler, ürünlerin standartlara uygunluğunu garanti eder.",
    ],
    category: "Üretim",
    date: "2026-02-15",
    readTime: "8 dk",
  },
  {
    slug: "kozmetik-ambalaj-trendleri-2026",
    title: "2026 Yılında Kozmetik Ambalaj Trendleri",
    excerpt: "Sürdürülebilirlik, akıllı ambalaj ve minimalist tasarım gibi öne çıkan kozmetik ambalaj trendlerini keşfedin.",
    content: [
      "2026 yılı kozmetik ambalaj sektöründe önemli değişimlerin yaşandığı bir dönem. Tüketici beklentileri, çevresel düzenlemeler ve teknolojik gelişmeler sektörü hızla dönüştürüyor.",
      "Sürdürülebilir ambalaj, 2026'nın en belirgin trendi. Geri dönüştürülebilir malzemeler, biyobozunur plastikler ve azaltılmış ambalaj kullanımı ön plana çıkıyor. rPET (geri dönüştürülmüş PET) kullanımı hızla artıyor.",
      "Akıllı ambalaj teknolojileri de yükselişte. QR kodları, NFC etiketler ve hologram güvenlik unsurları ile tüketicilere ürün hakkında detaylı bilgi sunulmakta ve marka güvenliği artırılmaktadır.",
      "Minimalist tasarım trendi devam ediyor. Sade etiketler, temiz tipografi ve lüks hissiyat yaratan ambalaj tasarımları hem estetik hem de çevresel açıdan tercih ediliyor.",
      "E-ticaretin büyümesiyle birlikte kargo dayanıklı kozmetik ambalaj çözümleri de önem kazanıyor. Hasar önleyici iç yapılar, hafif ama dayanıklı malzemeler bu alandaki talebi şekillendiriyor.",
    ],
    category: "Sektör",
    date: "2026-02-10",
    readTime: "6 dk",
  },
  {
    slug: "pet-malzeme-avantajlari",
    title: "PET Malzemenin Avantajları Nelerdir?",
    excerpt: "PET'in hafifliği, şeffaflığı, geri dönüşülebilirliği ve kozmetik ambalaj açısından sunduğu avantajlar.",
    content: [
      "PET, modern ambalaj endüstrisinin vazgeçilmez malzemesidir. Cam ile karşılaştırıldığında %90 daha hafif olan PET, lojistik maliyetleri önemli ölçüde düşürür.",
      "Mükemmel şeffaklık özelliği, ürünün raflarda öne çıkmasını sağlar. Tüketiciler ürünü görebildiği için satın alma kararlarını daha kolay verir.",
      "PET, %100 geri dönüştürülebilir bir malzemedir. Geri dönüşüm sürecinde orijinal özelliklerini büyük ölçüde korur ve yeniden kullanılabilir.",
      "Kozmetik güvenliği açısından PET, uluslararası standartlara uygun bir malzemedir. Ürünle temas eden yüzeyinde zararlı madde salınımı yapmaz.",
      "Kırılmaz yapısı sayesinde cam şişelere göre çok daha güvenlidir. Taşıma ve depolama sırasında hasar riski minimize edilir.",
    ],
    category: "Bilgi",
    date: "2026-02-05",
    readTime: "5 dk",
  },
  {
    slug: "iso-sertifika-onemi",
    title: "Kozmetik Ambalajda ISO Sertifikalarının Önemi",
    excerpt: "ISO 9001, ISO 14001 ve FSSC 22000 sertifikalarının ambalaj sektöründeki önemi.",
    content: [
      "ISO sertifikaları, bir firmanın üretim süreçlerinin uluslararası standartlara uygun olduğunu belgeler. Ambalaj sektöründe bu sertifikalar müşteri güveninin temelini oluşturur.",
      "ISO 9001 Kalite Yönetim Sistemi, ürün ve hizmet kalitesinin sürekli iyileştirilmesini sağlar. Müşteri memnuniyetini ön plana koyar.",
      "ISO 14001 Çevre Yönetim Sistemi, üretim süreçlerinin çevreye olan etkisini minimize etmeyi hedefler. Sürdürülebilir üretim anlayışının temelini oluşturur.",
      "FSSC 22000 sertifikası, tüketici ile temas eden ambalaj ürünlerinin güvenliğini garanti eder. Özellikle kozmetik sektörüne tedarik yapan firmalar için önemli bir kalite belgesidir.",
      "Sertifikalı olmak sadece kalite güvencesi değil, aynı zamanda pazara erişim kapısıdır. Uluslararası ticarette ve büyük perakende zincirlerinde sertifika şartı aranmaktadır.",
    ],
    category: "Kalite",
    date: "2026-01-28",
    readTime: "7 dk",
  },
  {
    slug: "dogru-sise-secimi",
    title: "İşletmeniz İçin Doğru Şişe Nasıl Seçilir?",
    excerpt: "Ürününüze uygun şişe seçerken dikkat etmeniz gereken kriterler.",
    content: [
      "Doğru ambalaj seçimi, ürün kalitesini ve marka algısını doğrudan etkiler. Şişe seçiminde dikkat edilmesi gereken birçok kriter bulunmaktadır.",
      "Hacim, en temel seçim kriteridir. Ürün miktarı, hedef pazar ve tüketim alışkanlıkları hacim belirlemede etkili olan faktörlerdir.",
      "Ağız çapı, kapak uyumluluğunu belirler. 18mm serum ve esansiyel yağ şişeleri için, 20mm kolonya ve parfüm şişeleri için, 24mm kozmetik ve kişisel bakım ürünleri için, 28mm sıvı sabun ve şampuan şişeleri için uygundur.",
      "Malzeme seçimi ürün ile uyumlu olmalıdır. PET kozmetik ve kişisel bakım için ideal iken, HDPE temizlik ürünleri için daha uygundur.",
      "Tasarım, marka kimliğini yansıtmalıdır. Standart kalıplar maliyet avantajı sağlarken, özel kalıplar markanızı farklılaştırır.",
    ],
    category: "Rehber",
    date: "2026-01-20",
    readTime: "6 dk",
  },
  {
    slug: "surdurulebilir-ambalaj",
    title: "Sürdürülebilir Ambalaj: Çevreye Duyarlı Üretim",
    excerpt: "Geri dönüştürülebilir malzemeler ve çevre dostu üretim süreçlerimiz hakkında.",
    content: [
      "Sürdürülebilir ambalaj, çevresel etkiyi minimize ederken ürün koruma fonksiyonunu sürdüren ambalaj yaklaşımıdır.",
      "PET, en yaygın geri dönüştürülen plastik türlerinden biridir. Bir PET şişe geri dönüştürüldüğünde yeni şişe, tekstil ürünü veya endüstriyel malzeme haline gelebilir.",
      "Kısmet Plastik olarak, üretim süreçlerimizde enerji verimliliğini artırmak, su tüketimini azaltmak ve atık minimizasyonu sağlamak için sürekli çalışıyoruz.",
      "rPET (geri dönüştürülmüş PET) kullanımını artırarak doğal kaynak tüketimini azaltıyoruz. rPET içerikli ürünlerimiz virgin PET ile aynı kalite standartlarını karşılar.",
      "Çevreye duyarlı üretim sadece bir tercih değil, gelecek nesillere karşı bir sorumluluktur. Bu bilinçle üretim süreçlerimizi sürekli geliştiriyoruz.",
    ],
    category: "Sürdürülebilirlik",
    date: "2026-01-12",
    readTime: "5 dk",
  },
];

async function importData() {
  // --- Categories ---
  console.log('Importing 8 categories...');
  const { data: catData, error: catError } = await supabase
    .from('categories')
    .upsert(
      categories.map(c => ({
        slug: c.slug,
        name: c.name,
        description: c.description,
        product_count: c.productCount,
      })),
      { onConflict: 'slug' }
    )
    .select();

  if (catError) {
    console.error('Category import FAILED:', catError.message);
    return;
  }
  console.log(`Categories imported: ${catData.length} rows`);

  // --- Products (batches of 10) ---
  console.log(`\nImporting ${products.length} products...`);
  let productSuccess = 0;
  for (let i = 0; i < products.length; i += 10) {
    const batch = products.slice(i, i + 10);
    const { data: prodData, error: prodError } = await supabase
      .from('products')
      .upsert(
        batch.map(p => ({
          slug: p.slug,
          name: p.name,
          category_slug: p.category,
          description: p.description,
          short_description: p.shortDescription,
          volume: p.volume || null,
          weight: p.weight || null,
          neck_diameter: p.neckDiameter || null,
          height: p.height || null,
          diameter: p.diameter || null,
          material: p.material,
          colors: p.colors,
          color_codes: p.colorCodes || null,
          model: p.model || null,
          shape: p.shape || null,
          surface_type: p.surfaceType || null,
          compatible_caps: p.compatibleCaps || null,
          min_order: p.minOrder,
          in_stock: p.inStock,
          featured: p.featured,
          specs: p.specs,
        })),
        { onConflict: 'slug' }
      )
      .select();

    if (prodError) {
      console.error(`  Product batch ${i}-${i + batch.length} FAILED:`, prodError.message);
    } else {
      productSuccess += prodData.length;
      console.log(`  Products batch ${i}-${i + batch.length} OK (${prodData.length} rows)`);
    }
  }
  console.log(`Products imported: ${productSuccess}/${products.length}`);

  // --- Blog Posts ---
  console.log(`\nImporting ${blogPosts.length} blog posts...`);
  const { data: blogData, error: blogError } = await supabase
    .from('blog_posts')
    .upsert(
      blogPosts.map(b => ({
        slug: b.slug,
        title: b.title,
        excerpt: b.excerpt,
        content: b.content,
        category: b.category,
        date: b.date,
        read_time: b.readTime,
        featured: false,
      })),
      { onConflict: 'slug' }
    )
    .select();

  if (blogError) {
    console.error('Blog posts import FAILED:', blogError.message);
  } else {
    console.log(`Blog posts imported: ${blogData.length} rows`);
  }

  console.log('\n--- Import complete ---');
}

importData().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
